// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntxcazyoqzbezmjwafvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eGNhenlvcXpiZXptandhZnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTQ3OTMsImV4cCI6MjA2MjAzMDc5M30.rCP2pdRObnpxC-O7XVCv00gmOysPj10FXH1yuA34HJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);